In [ ]:
# import library
import numpy as np

In [ ]:
#Basics
print(np.array([1,2,3]))

[1 2 3]


In [ ]:
# 2-d array
b = np.array([[1,2],[3,4]])

In [ ]:
# dimentions(shape of the array)
b.shape

(2, 2)

In [ ]:
b.ndim # number of dimentions

2

In [ ]:
b.dtype # return data type of the values

dtype('int64')

In [ ]:
aa = np.array([1,2,3], dtype='int16') #can specify the data type you want to use in the array default type is 'int32'
aa.dtype

dtype('int16')

In [ ]:
# return sthe number of items in the array
aa.size

3

In [ ]:
# itemsize returns the byte size of the each item in that array
aa.itemsize

2

In [ ]:
b.itemsize

8

In [ ]:
# total size of the array(total number of bytes)
b.size * b.itemsize

32

In [ ]:
# other way for total size
b.nbytes

32

In [ ]:
# accessing,working with the values of the array

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a.shape

(2, 7)

In [ ]:
# accessing a[row,col]
print(a[1,3])

11


In [ ]:
a[1,-4] # negative indexing

np.int64(11)

In [ ]:
a[1,:] # to access a completre row

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[:,0]  # accessing a complete column (0th column)

array([1, 8])

In [ ]:
#[start,end,step] similar to lists but this is to specify for each row, column in the multi dimentional array
a[0,1:6:3] # 0th row elemnts in that 1st to 6th column elements and elements that are three steps apart only

array([2, 5])

In [ ]:
a[:,0:7:2] #all rows inn that all columns values that are 2 stepa apart 7th index is excluded

array([[ 1,  3,  5,  7],
       [ 8, 10, 12, 14]])

In [ ]:
#changing values
print(a[1,4])
a[1,4] = 667

667


In [ ]:
print(a)

[[  1   2   3   4   5   6   7]
 [  8   9  10  11 667  13  14]]


In [ ]:
a[0,:] = 4 # changing all the row values (you can also mention different values specifying values as a list of same dimentions)
print(a)

[[  4   4   4   4   4   4   4]
 [  8   9  10  11 667  13  14]]


In [ ]:
# 3D example

In [ ]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# accessing
d[1,1,:]

array([7, 8])

In [ ]:
# for replacing use same dimentional array
d[1,1,:] = [4,4]
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [4 4]]]


In [ ]:
# inititalizing diffent types of arrays

In [ ]:
# Zeros
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# ones
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
print(np.zeros((2,2,2)))
print(np.ones((2,3,2), 'int32')) # array of two (3,2) shape arrays
# you can specify the datatype

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [ ]:
# to make array of different values
np.full((4,2),77)

array([[77, 77],
       [77, 77],
       [77, 77],
       [77, 77]])

In [ ]:
# full_like method that takes the shape of the other array we give a s a reference
np.full_like(a,4) #(array,value)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# random decimal numbers (rand generates values between 0 and 1)
np.random.rand(4,2)

array([[0.70445486, 0.32584728],
       [0.04474932, 0.38462433],
       [0.93449064, 0.03341173],
       [0.71591004, 0.81341033]])

In [ ]:
# for the sahpe of other array we have
np.random.random_sample(a.shape)

array([[7.05494975e-01, 8.87553759e-01, 1.55354773e-01, 6.79850061e-01,
        6.25634312e-01, 6.92328803e-01, 4.64145393e-01],
       [7.99235035e-01, 4.04367025e-01, 8.99030869e-01, 3.18623538e-04,
        7.72192013e-01, 7.47883680e-02, 1.82464948e-01]])

In [ ]:
# for random integers
np.random.randint(2,11,size=(4,2)) #(low, high , size =(rows,cols)) low, high for random values generation between those integers
# if no low values then it starts with 0 by default

array([[ 5,  7],
       [ 7,  5],
       [ 2,  9],
       [10,  7]])

In [ ]:
# identity matrix
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
# repeat an array
print(aa)
print(np.repeat(aa,4)) # repeats each individual elements of the array bu the specified number (array to repeat, number for how many times)

[1 2 3]
[1 1 1 1 2 2 2 2 3 3 3 3]


In [ ]:
# you can add axis to specify how you want to repeat the values in the array
aa = np.array([[1,2,3]]) #2D array
aa = np.repeat(aa,4, axis=1) # repeats by adding new rows to the array
print(aa)
bb = np.array([[1,2,3]])
bb = np.repeat(bb,4, axis=0) # repeats by adding new columns to the array
print(bb)

[[1 1 1 1 2 2 2 2 3 3 3 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# examnple
a = np.ones((5,5),dtype='int32')
b = np.zeros((3,3))
b[1,1] = 9
a[1:4,1:4] = b
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#copying elements simlar to python shallow copying vs deep copying

In [ ]:
a = np.array([1,2,3])
b = a
print(a)
print(b)

[1 2 3]
[1 2 3]


In [ ]:
b[1]= 999
print(b)
print(a)
# this is shallow copying just refering to the same data by two variables

[  1 999   3]
[  1 999   3]


In [ ]:
b = np.copy(a) #actual copying or b=a.copy()
b[1] = 777
print(b)
print(a)

[  1 777   3]
[  1 999   3]


In [ ]:
b = a.copy()
print(b)

[  1 999   3]


In [ ]:
#Math runs operations on invidual elements of the array

In [ ]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a+2

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
a-2

array([-1,  0,  1,  2,  3,  4,  5])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [ ]:
a//2 # floor division

array([0, 1, 1, 2, 2, 3, 3])

In [ ]:
a%2

array([1, 0, 1, 0, 1, 0, 1])

In [ ]:
#can use asssignment operatoes += , -=, /= ,*= do operation and assingning back the values to the array
a+=4
a

array([ 5,  6,  7,  8,  9, 10, 11])

In [ ]:
b=np.array([9,8,7,6,5,4,3])
print(a+b) #need same dimentions array to operate

[14 14 14 14 14 14 14]


In [ ]:
a ** 4 # power

array([  625,  1296,  2401,  4096,  6561, 10000, 14641])

In [ ]:
#sin trignometry
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021])

In [ ]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153,  0.0044257 ])

In [ ]:
# Linear Algebra

In [ ]:
a = np.full((2,3),3)
b = np.full((3,2),4)
print(a)
print(b)

[[3 3 3]
 [3 3 3]]
[[4 4]
 [4 4]
 [4 4]]


In [ ]:
# matrix multiplication
np.matmul(a,b)

array([[36, 36],
       [36, 36]])

In [ ]:
# determinent
c = np.identity(5)
np.linalg.det(c)

np.float64(1.0)

In [ ]:
#statistics

In [ ]:
a = np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [ ]:
print(np.min(a))
print(np.max(a))
print(np.sum(a))

1
6
21


In [ ]:
a = np.full((3,5),7)
print(a)
print(np.sum(a, axis=0)) # sum of each column
print(np.sum(a, axis=1)) # sum row wise

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
[21 21 21 21 21]
[35 35 35]


In [ ]:
#reorganizing arrays

In [ ]:
print(a)
print(a.shape)
print(a.reshape((5,3)))
print(a.reshape((3,5,1)))

[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
(3, 5)
[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]
[[[7]
  [7]
  [7]
  [7]
  [7]]

 [[7]
  [7]
  [7]
  [7]
  [7]]

 [[7]
  [7]
  [7]
  [7]
  [7]]]


In [ ]:
# vertically stacking
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1,v1]) # you can add mutliple copies of a single array

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [ ]:
# horizantal stacking
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [214]:
# boolean masking

In [216]:
a = np.random.randint(1,100,size=(5,5))
print(a)

[[ 9 69 35 12 63]
 [64 91 30 80 93]
 [88 41 56 72 60]
 [60 73 67 78 70]
 [ 2 73 11  5 66]]


In [218]:
a > 50

array([[False,  True, False, False,  True],
       [ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True, False, False,  True]])

In [219]:
a <= 40

array([[ True, False,  True,  True, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False,  True,  True, False]])

In [220]:
# you can add the data from txt file using genfromtxt() function ('file name', delimiter=',') for comme seperated values

In [222]:
print(a)

[[ 9 69 35 12 63]
 [64 91 30 80 93]
 [88 41 56 72 60]
 [60 73 67 78 70]
 [ 2 73 11  5 66]]


In [226]:
print(a[[2,3,4]]) #indexing the values using the lists

[[88 41 56 72 60]
 [60 73 67 78 70]
 [ 2 73 11  5 66]]


In [229]:
np.any(a>40 , axis=0) # asking if any value is greater than 40 in each column

array([ True,  True,  True,  True,  True])

In [232]:
np.all(a>40 , axis=0) # asking if all the values are greater than 40 in each column

array([False,  True, False, False,  True])

In [233]:
# if axis=1 it checks row wise

In [235]:
np.any(a>40 , axis=1) # asking if any value is greater than 40 in each column

array([ True,  True,  True,  True,  True])

In [237]:
((a>50) & (a<80)) # multiple conditions using '&'

array([[False,  True, False, False,  True],
       [ True, False, False, False, False],
       [False, False,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True, False, False,  True]])

In [241]:
((a>50) | (a<80)) # multiple conditions using '&'

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [244]:
~(a>50)# ~ not

array([[ True, False,  True,  True, False],
       [False, False,  True, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False],
       [ True, False,  True,  True, False]])

In [245]:
#example

In [248]:
# Create an array with values from 1 to 30
arr = np.arange(1, 31)

# Reshape the array to (6, 5)
arr = arr.reshape((6,5))

# Print the array
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [250]:
arr[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [260]:
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [262]:
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])